language: node_js
node_js:
  - 4.4
install:
  - npm install
before_script:
  - npm install -g gulp
script: npm build
branches:
  only:
  - master
after_failure: "cat /home/travis/build/MarcLoupias/my-cv/npm-debug.log"
