language: node_js
node_js:
  - 6
before_install:
  - npm install -g npm@6.4.1
install:
  - npm install
  - npm --version
before_script:
  - npm test
script:
  - npm run-script build
branches:
  only:
  - master
after_failure: "cat /home/travis/build/MarcLoupias/my-cv/npm-debug.log"
