language: node_js
node_js:
  - 4.4
before_install:
  - npm install -g npm@3.10.5
  - npm install -g bower@1.7.9
install:
  - npm install
  - bower install
script: npm build
branches:
  only:
  - master
after_failure: "cat /home/travis/build/MarcLoupias/my-cv/npm-debug.log"
