language: node_js
node_js:
  - 6
before_install:
  - npm install -g npm@5.5.1
  - npm install -g bower@1.8.0
install:
  - npm install
  - bower install
  - npm --version
  - bower --version
before_script:
  - npm test
  - npm e2e-headless
script: npm build
branches:
  only:
  - master
after_failure: "cat /home/travis/build/MarcLoupias/my-cv/npm-debug.log"
